version: '3.8'

services:
  # 1. Servicio de la Base de Datos
  postgres_db:
    image: postgres:15-alpine
    container_name: cusco_limpio_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cusco_limpio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Servicio de nuestro Backend NestJS
  backend_api:
    build:
      context: ./backend    # Le dice a Docker que busque el Dockerfile dentro de la carpeta backend
      dockerfile: Dockerfile
    container_name: cusco_limpio_backend
    ports:
      - "3000:3000"         # Abre el puerto 3000 para que tu frontend pueda conectarse
    environment:
      DATABASE_URL: "postgresql://admin:password123@postgres_db:5432/cusco_limpio"
    depends_on:
      - postgres_db         # Espera a que la base de datos suba antes de iniciar el backend

volumes:
  postgres_data: